# -*- coding: utf-8 -*-

import csv
import re
import argparse
from xml.dom.minidom import parseString
from xml.etree import ElementTree as ET
from datetime import datetime

def parse_arguments():
    parser = argparse.ArgumentParser(description="Convertit un fichier CSV en format Gramps XML.")
    parser.add_argument("input_csv", help="Chemin vers le fichier CSV d'entrée.")
    parser.add_argument("output_xml", help="Chemin vers le fichier XML de sortie.")
    parser.add_argument("--wikipedia", "-w", action="store_true", help="Activer la recherche Wikipedia pour enrichir les descriptions.")
    return parser.parse_args()

def dms_to_decimal(dms):
    """Convertit les coordonnées DMS en décimal."""
    match = re.match(r"(\d+)° (\d+)' ([\d\.]+)\" ([NSEW])", dms.strip())
    if match:
        degrees, minutes, seconds, direction = match.groups()
        decimal = float(degrees) + float(minutes)/60 + float(seconds)/3600
        if direction in ('S', 'W'):
            decimal *= -1
        return decimal
    return None

def parse_coords(coords_str):
    """Extrait et convertit les coordonnées DMS en décimal."""
    if not coords_str:
        return None, None
    parts = coords_str.split(',')
    if len(parts) == 2:
        lat = dms_to_decimal(parts[0].strip())
        lon = dms_to_decimal(parts[1].strip())
        return lat, lon
    return None, None

def get_wikipedia_summary(title, use_wikipedia):
    """Récupère un résumé Wikipedia si l'option est activée."""
    if not use_wikipedia:
        return None
    try:
        import wikipedia
        wikipedia.set_lang("fr")
        return wikipedia.summary(title, sentences=3, auto_suggest=False)
    except ImportError:
        print("Le module 'wikipedia' n'est pas installé. Utilisez `pip install wikipedia` pour l'activer.")
        return None
    except wikipedia.exceptions.PageError:
        return None
    except wikipedia.exceptions.DisambiguationError as e:
        if e.options:
            return wikipedia.summary(e.options[0], sentences=3, auto_suggest=False)
        return None
    except Exception as e:
        print("Erreur Wikipedia pour {}: {}".format(title, e))
        return None

def csv_to_gramps_xml(csv_file_path, output_xml_file_path, use_wikipedia):
    with open(csv_file_path, mode='r', encoding='utf-8') as csv_file:
        csv_reader = csv.DictReader(csv_file)
        data = [row for row in csv_reader]

    total_rows = len(data)
    print("Conversion de {} entrées...".format(total_rows))

    # Créer la structure XML de base pour Gramps 5.2
    database = ET.Element('database', xmlns="http://gramps-project.org/xml/1.7.1/")

    # En-tête avec la version de Gramps
    header = ET.SubElement(database, 'header')
    ET.SubElement(
        header, 'created',
        date=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        version="5.2.0"
    )
    ET.SubElement(header, 'researcher', name="Generated by script")

    # Sections principales (comme dans example.gramps)
    objects = ET.SubElement(database, 'objects')
    places = ET.SubElement(objects, 'places')
    notes = ET.SubElement(objects, 'notes')

    # Compteurs pour les handles (format Gramps : _xxxxxxxx)
    place_handle = 100000000
    note_handle = 400000000

    # Dictionnaire pour stocker les handles des notes
    note_handles = {}

    # Traitement des notes
    for i, row in enumerate(data, 1):
        print("\rTraitement des notes : {}/{} ({}%)".format(i, total_rows, int(i/total_rows*100)), end="")

        description = row.get('Description', '').strip()
        wiki_summary = get_wikipedia_summary(row['Titre'], use_wikipedia)

        if wiki_summary:
            description = "{}\n\n--- Wikipedia ---\n{}".format(description, wiki_summary)

        if description:
            note = ET.SubElement(
                notes, 'note',
                handle="_{}".format(note_handle),
                change=str(int(datetime.now().timestamp())),
                id="N{}".format(note_handle),
                type="Html code"
            )
            text = ET.SubElement(note, 'text')
            text.text = "<b>{}</b><p>{}</p>".format(row['Titre'], description.replace(chr(10), '<br>'))
            note_handles[row['Titre']] = "_{}".format(note_handle)
            note_handle += 1

    print()  # Saut de ligne après la boucle des notes

    # Traitement des lieux
    for i, row in enumerate(data, 1):
        print("\rTraitement des lieux : {}/{} ({}%)".format(i, total_rows, int(i/total_rows*100)), end="")

        place = ET.SubElement(
            places, 'placeobj',
            handle="_{}".format(place_handle),
            change=str(int(datetime.now().timestamp())),
            id="P{}".format(place_handle),
            type="Place"
        )
        ptitle = ET.SubElement(place, 'ptitle')
        ptitle.text = row.get('Titre', 'Inconnu')

        pname = ET.SubElement(place, 'pname')
        pname.set('value', row.get('Titre', 'Inconnu'))

        lat, lon = parse_coords(row.get('Coordonnées', ''))
        if lat and lon:
            coord = ET.SubElement(place, 'coord')
            coord.set('lat', "{:.6f}".format(lat))
            coord.set('long', "{:.6f}".format(lon))

        if row['Titre'] in note_handles:
            noteref = ET.SubElement(place, 'noteref')
            noteref.set('hlink', note_handles[row['Titre']])

        place_handle += 1

    print()  # Saut de ligne après la boucle des lieux

    xml_str = ET.tostring(database, encoding='utf-8').decode('utf-8')
    doctype_declaration = '''<!DOCTYPE database PUBLIC "-//Gramps//DTD Gramps XML 1.7.1//EN"
"http://gramps-project.org/xml/1.7.1/grampsxml.dtd">'''
    xml_str = "{}\n{}".format(doctype_declaration, xml_str)
    dom = parseString(xml_str)

    with open(output_xml_file_path, 'w', encoding='utf-8') as f:
        dom.writexml(f, indent='  ', addindent='  ', newl='\n', encoding='utf-8')

    print("Conversion terminée avec succès !")

def main():
    args = parse_arguments()
    csv_to_gramps_xml(args.input_csv, args.output_xml, args.wikipedia)

if __name__ == "__main__":
    main()
