# -*- coding: utf-8 -*-

import csv
import re
import argparse
from xml.dom.minidom import parseString
from xml.etree import ElementTree as ET
from datetime import datetime

def parse_arguments():
    parser = argparse.ArgumentParser(description="Convertit un fichier CSV en format Gramps XML.")
    parser.add_argument("input_csv", help="Chemin vers le fichier CSV d'entrée.")
    parser.add_argument("output_xml", help="Chemin vers le fichier XML de sortie.")
    parser.add_argument("--wikipedia", "-w", action="store_true", help="Activer la recherche Wikipedia.")
    return parser.parse_args()

def dms_to_decimal(dms):
    """Convertit les coordonnées DMS en décimal."""
    match = re.match(r"(\d+)° (\d+)' ([\d\.]+)\" ([NSEW])", dms.strip())
    if match:
        degrees, minutes, seconds, direction = match.groups()
        decimal = float(degrees) + float(minutes)/60 + float(seconds)/3600
        if direction in ('S', 'W'):
            decimal *= -1
        return decimal
    return None

def parse_coords(coords_str):
    """Extrait et convertit les coordonnées DMS en décimal."""
    if not coords_str:
        return None, None
    parts = coords_str.split(',')
    if len(parts) == 2:
        lat = dms_to_decimal(parts[0].strip())
        lon = dms_to_decimal(parts[1].strip())
        return lat, lon
    return None, None

def extract_refs(text):
    """Extrait les balises <ref>...</ref> d'un texte et retourne une liste de références."""
    ref_pattern = re.compile(r'<ref>(.*?)</ref>', re.DOTALL)
    refs = ref_pattern.findall(text)
    return refs

def extract_sources_from_ref(ref):
    """Extrait les sources des modèles {{Source|...}} dans une référence."""
    source_pattern = re.compile(r'\{\{Source\|(.*?)\}\}')
    sources = source_pattern.findall(ref)
    return sources

def parse_ref(ref):
    """Parse une référence pour extraire les sources et les métadonnées."""
    url = None
    meta = {}
    sources = extract_sources_from_ref(ref)

    if ref.strip().startswith("http"):
        parts = ref.split()
        url = parts[0]
        meta["consulté"] = " ".join(parts[1:]) if len(parts) > 1 else ""

    return url, meta, sources

def extract_gallery(text):
    """Extrait les images d'une balise <gallery> et retourne une liste de tuples (fichier, description)."""
    gallery_pattern = re.compile(r'<gallery>(.*?)</gallery>', re.DOTALL)
    match = gallery_pattern.search(text)
    if not match:
        return []

    gallery_content = match.group(1)
    image_pattern = re.compile(r'Fichier:([^\|]+)\|([^\n]+)')
    images = image_pattern.findall(gallery_content)
    return images

def get_wikipedia_summary(title, use_wikipedia):
    """Récupère un résumé Wikipedia si l'option est activée."""
    if not use_wikipedia:
        return None
    try:
        import wikipedia
        wikipedia.set_lang("fr")
        return wikipedia.summary(title, sentences=3, auto_suggest=False)
    except ImportError:
        print("Le module 'wikipedia' n'est pas installé. Utilisez `pip3 install wikipedia` pour l'activer.")
        return None
    except wikipedia.exceptions.PageError:
        return None
    except wikipedia.exceptions.DisambiguationError as e:
        if e.options:
            return wikipedia.summary(e.options[0], sentences=3, auto_suggest=False)
        return None
    except Exception as e:
        print("Erreur Wikipedia pour {}: {}".format(title, e))
        return None

def csv_to_gramps_xml(csv_file_path, output_xml_file_path, use_wikipedia):
    with open(csv_file_path, mode='r', encoding='utf-8') as csv_file:
        csv_reader = csv.DictReader(csv_file, delimiter=',', quotechar='"')
        data = [row for row in csv_reader]

    total_rows = len(data)
    print("Conversion de {} entrées...".format(total_rows))

    # Créer la structure XML de base pour Gramps 5.2
    database = ET.Element('database', xmlns="http://gramps-project.org/xml/1.7.1/")

    # En-tête avec la version de Gramps
    header = ET.SubElement(database, 'header')
    ET.SubElement(
        header, 'created',
        date=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        version="5.2.0"
    )
    ET.SubElement(header, 'researcher', name="Generated by script")

    # Sections principales (comme dans example.gramps)
    objects = ET.SubElement(database, 'objects')

    # Compteurs pour les handles (format Gramps : _xxxxxxxx)
    place_handle = 100000000
    note_handle = 400000000

    # Dictionnaire pour stocker les handles des notes
    note_handles = {}
    source_handles = {}
    next_source_handle = 500000000
    media_handles = {}
    next_media_handle = 600000000

    # Traitement des notes, en premier
    for i, row in enumerate(data, 1):
        print("\rTraitement des notes : {}/{} ({}%)".format(i, total_rows, int(i/total_rows*100)), end="")

        description = row.get('Description', '').strip()
        wiki_summary = get_wikipedia_summary(row['Titre'], use_wikipedia)

        if wiki_summary:
            description = "{}\n\n--- Wikipedia ---\n{}".format(description, wiki_summary)

        # Extraction des références
        refs = extract_refs(description)

        # Création des objets source pour chaque référence unique
        for ref in refs:
            url, meta, sources = parse_ref(ref)

            # Création d'une source pour l'URL si elle existe
            if url and url not in source_handles:
                source = ET.SubElement(
                    objects, 'source',
                    handle="_{}".format(next_source_handle),
                    id="S{}".format(next_source_handle),
                    change=str(int(datetime.now().timestamp()))
                )
                stitle = ET.SubElement(source, 'stitle')
                stitle.text = url
                if meta.get("consulté"):
                    spubinfo = ET.SubElement(source, 'spubinfo')
                    spubinfo.text = meta["consulté"]
                source_handles[url] = "_{}".format(next_source_handle)
                next_source_handle += 1

            # Création de sources pour chaque modèle {{Source|...}}
            for source_model in sources:
                if source_model not in source_handles:
                    source = ET.SubElement(
                        objects, 'source',
                        handle="_{}".format(next_source_handle),
                        id="S{}".format(next_source_handle),
                        change=str(int(datetime.now().timestamp()))
                    )
                    stitle = ET.SubElement(source, 'stitle')
                    stitle.text = source_model
                    source_handles[source_model] = "_{}".format(next_source_handle)
                    next_source_handle += 1

        # Remplacement des balises <ref> et {{Source|...}} par des références Gramps
        for ref in refs:
            url, meta, sources = parse_ref(ref)
            ref_replacement = []

            if url and url in source_handles:
                ref_replacement.append('<sourceref hlink="{}"/>'.format(source_handles[url]))

            for source_model in sources:
                if source_model in source_handles:
                    ref_replacement.append('<sourceref hlink="{}"/>'.format(source_handles[source_model]))

            if ref_replacement:
                description = description.replace('<ref>{}</ref>'.format(ref), " ".join(ref_replacement), 1)

        # Extraction des galeries
        images = extract_gallery(description)

        # Création des objets média pour chaque image
        for image_file, image_desc in images:
            if image_file not in media_handles:
                media = ET.SubElement(
                    objects, 'object',
                    handle="_{}".format(next_media_handle),
                    id="O{}".format(next_media_handle),
                    type="Media",
                    change=str(int(datetime.now().timestamp()))
                )
                file = ET.SubElement(media, 'file')
                file.set('src', image_file)
                file.set('mime', 'image/jpeg')
                file.set('description', image_desc)

                media_handles[image_file] = "_{}".format(next_media_handle)
                next_media_handle += 1

        # Remplacement des balises <gallery> par des références Gramps dans la description
        if images:
            media_refs = []
            for image_file, image_desc in images:
                if image_file in media_handles:
                    media_refs.append('<objref hlink="{}"/>'.format(media_handles[image_file]))

            gallery_replacement = "\n".join(media_refs)
            description = re.sub(r'<gallery>.*?</gallery>', gallery_replacement, description, flags=re.DOTALL)

        if description:
            note = ET.SubElement(
                objects, 'note',
                handle="_{}".format(note_handle),
                change=str(int(datetime.now().timestamp())),
                id="N{}".format(note_handle),
                type="Html code"
            )
            text = ET.SubElement(note, 'text')
            text.text = "<b>{}</b><p>{}</p>".format(row['Titre'], description.replace(chr(10), '<br>'))

            note_handles[row['Titre']] = "_{}".format(note_handle)
            note_handle += 1

    # Ajouter les lieux et référencer les notes
    for i, row in enumerate(data, 1):
        print("\rTraitement des lieux : {}/{} ({}%)".format(i, total_rows, int(i/total_rows*100)), end="")

        place = ET.SubElement(
            objects, 'placeobj',
            handle="_{}".format(place_handle),
            change=str(int(datetime.now().timestamp())),
            id="P{}".format(place_handle),
            type="Place"
        )
        ptitle = ET.SubElement(place, 'ptitle')
        ptitle.text = row.get('Titre', 'Inconnu')

        # Nom du lieu
        pname = ET.SubElement(place, 'pname')
        pname.set('value', row.get('Titre', 'Inconnu'))

        # Coordonnées
        lat, lon = parse_coords(row.get('Coordonnées', ''))
        if lat and lon:
            coord = ET.SubElement(place, 'coord')
            coord.set('lat', "{:.6f}".format(lat))
            coord.set('long', "{:.6f}".format(lon))

        # Référence à la note si elle existe
        if row['Titre'] in note_handles:
            noteref = ET.SubElement(place, 'noteref')
            noteref.set('hlink', note_handles[row['Titre']])

        place_handle += 1

    print()  # Saut de ligne après la boucle des lieux

    # Convertir en chaîne XML
    xml_str = ET.tostring(database, encoding='utf-8').decode('utf-8')

    # Ajouter la déclaration DOCTYPE pour Gramps 5.2
    doctype_declaration = '''<!DOCTYPE database PUBLIC "-//Gramps//DTD Gramps XML 1.7.1//EN"
"http://gramps-project.org/xml/1.7.1/grampsxml.dtd">'''

    # Formater le XML avec minidom
    xml_str = "{}\n{}".format(doctype_declaration, xml_str)
    dom = parseString(xml_str)

    # Écrire le fichier
    with open(output_xml_file_path, 'w', encoding='utf-8') as f:
        dom.writexml(f, indent='  ', addindent='  ', newl='\n', encoding='utf-8')

    print("Conversion terminée avec succès !")

def main():
    args = parse_arguments()
    csv_to_gramps_xml(args.input_csv, args.output_xml, args.wikipedia)

if __name__ == "__main__":
    main()
